
// This file has been generated by the GUI designer. Do not modify.
namespace vostrusInfo
{
	public partial class telaCadastro
	{
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Entry entry2;
		private global::Gtk.Entry entry4;
		private global::Gtk.Entry entry3;
		private global::Gtk.Entry entry1;
		private global::Gtk.Label label4;
		private global::Gtk.Label label3;
		private global::Gtk.Label label2;
		private global::Gtk.Label name;
		private global::Gtk.Label res;
		private global::Gtk.Button button2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget vostrusInfo.telaCadastro
			this.Name = "vostrusInfo.telaCadastro";
			this.Title = global::Mono.Unix.Catalog.GetString ("telaCadastro");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child vostrusInfo.telaCadastro.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entry2 = new global::Gtk.Entry ();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '●';
			this.fixed2.Add (this.entry2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.entry2]));
			w1.X = 243;
			w1.Y = 85;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entry4 = new global::Gtk.Entry ();
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '●';
			this.fixed2.Add (this.entry4);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.entry4]));
			w2.X = 243;
			w2.Y = 167;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entry3 = new global::Gtk.Entry ();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '●';
			this.fixed2.Add (this.entry3);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.entry3]));
			w3.X = 243;
			w3.Y = 124;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.fixed2.Add (this.entry1);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.entry1]));
			w4.X = 244;
			w4.Y = 46;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Cartão Crédito");
			this.fixed2.Add (this.label4);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label4]));
			w5.X = 32;
			w5.Y = 167;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Plano");
			this.label3.MaxWidthChars = 49;
			this.fixed2.Add (this.label3);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label3]));
			w6.X = 34;
			w6.Y = 127;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("email");
			this.fixed2.Add (this.label2);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label2]));
			w7.X = 32;
			w7.Y = 90;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.name = new global::Gtk.Label ();
			this.name.Name = "name";
			this.name.LabelProp = global::Mono.Unix.Catalog.GetString ("Nome Completo");
			this.fixed2.Add (this.name);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.name]));
			w8.X = 28;
			w8.Y = 55;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.res = new global::Gtk.Label ();
			this.res.Name = "res";
			this.res.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.fixed2.Add (this.res);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.res]));
			w9.X = 450;
			w9.Y = 239;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Cadastrar");
			this.fixed2.Add (this.button2);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.button2]));
			w10.X = 234;
			w10.Y = 316;
			this.Add (this.fixed2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 681;
			this.DefaultHeight = 414;
			this.Show ();
			this.fixed2.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnFixed2DeleteEvent);
			this.fixed2.Removed += new global::Gtk.RemovedHandler (this.OnFixed2Removed);
			this.entry1.Activated += new global::System.EventHandler (this.OnEntry1Activated);
			this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
		}
	}
}
