
// This file has been generated by the GUI designer. Do not modify.
namespace vostrusInfo
{
	public partial class MainSreen
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action UsuarioAction;
		private global::Gtk.Action cadastrarUsuarioAction;
		private global::Gtk.Action ProdutoAction;
		private global::Gtk.Action cadastrarProdutoAction;
		private global::Gtk.Action ProutoAction;
		private global::Gtk.Action cadastroProdutoAction;
		private global::Gtk.Action consultaProdutoAction;
		private global::Gtk.Action consultarProdutoAction;
		private global::Gtk.Action cadastrarUsuarioAction1;
		private global::Gtk.Action consultarUsuarioAction;
		private global::Gtk.Action sairAction;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.MenuBar menubar1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget vostrusInfo.MainSreen
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.UsuarioAction = new global::Gtk.Action ("UsuarioAction", global::Mono.Unix.Catalog.GetString ("Usuario"), null, null);
			this.UsuarioAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Usuario");
			w1.Add (this.UsuarioAction, null);
			this.cadastrarUsuarioAction = new global::Gtk.Action ("cadastrarUsuarioAction", global::Mono.Unix.Catalog.GetString ("cadastrarUsuario"), null, null);
			this.cadastrarUsuarioAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("ConsultarUsuario");
			w1.Add (this.cadastrarUsuarioAction, null);
			this.ProdutoAction = new global::Gtk.Action ("ProdutoAction", global::Mono.Unix.Catalog.GetString ("Produto"), null, null);
			this.ProdutoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("cadastroUsuario");
			w1.Add (this.ProdutoAction, null);
			this.cadastrarProdutoAction = new global::Gtk.Action ("cadastrarProdutoAction", global::Mono.Unix.Catalog.GetString ("cadastrarProduto"), null, null);
			this.cadastrarProdutoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("consultarUsuario");
			w1.Add (this.cadastrarProdutoAction, null);
			this.ProutoAction = new global::Gtk.Action ("ProutoAction", global::Mono.Unix.Catalog.GetString ("Prouto"), null, null);
			this.ProutoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Prouto");
			w1.Add (this.ProutoAction, null);
			this.cadastroProdutoAction = new global::Gtk.Action ("cadastroProdutoAction", global::Mono.Unix.Catalog.GetString ("cadastroProduto"), null, null);
			this.cadastroProdutoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("cadastroProduto");
			w1.Add (this.cadastroProdutoAction, null);
			this.consultaProdutoAction = new global::Gtk.Action ("consultaProdutoAction", global::Mono.Unix.Catalog.GetString ("consultaProduto"), null, null);
			this.consultaProdutoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("consultaProduto");
			w1.Add (this.consultaProdutoAction, null);
			this.consultarProdutoAction = new global::Gtk.Action ("consultarProdutoAction", global::Mono.Unix.Catalog.GetString ("consultarProduto"), null, null);
			this.consultarProdutoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("consultaProduto");
			w1.Add (this.consultarProdutoAction, null);
			this.cadastrarUsuarioAction1 = new global::Gtk.Action ("cadastrarUsuarioAction1", global::Mono.Unix.Catalog.GetString ("cadastrarUsuario"), null, null);
			this.cadastrarUsuarioAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("cadastrarUsuario");
			w1.Add (this.cadastrarUsuarioAction1, null);
			this.consultarUsuarioAction = new global::Gtk.Action ("consultarUsuarioAction", global::Mono.Unix.Catalog.GetString ("consultarUsuario"), null, null);
			this.consultarUsuarioAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("consultarUsuario");
			w1.Add (this.consultarUsuarioAction, null);
			this.sairAction = new global::Gtk.Action ("sairAction", global::Mono.Unix.Catalog.GetString ("sair"), null, null);
			this.sairAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("sair");
			w1.Add (this.sairAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "vostrusInfo.MainSreen";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainSreen");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child vostrusInfo.MainSreen.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='UsuarioAction' action='UsuarioAction'><menuitem name='cadastrarUsuarioAction1' action='cadastrarUsuarioAction1'/><menuitem name='consultarUsuarioAction' action='consultarUsuarioAction'/></menu><menu name='ProdutoAction' action='ProdutoAction'><menuitem name='cadastrarProdutoAction' action='cadastrarProdutoAction'/><menuitem name='consultarProdutoAction' action='consultarProdutoAction'/></menu><menu name='sairAction' action='sairAction'/></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.fixed1.Add (this.menubar1);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.menubar1]));
			w2.X = 3;
			w2.Y = 6;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 724;
			this.DefaultHeight = 359;
			this.Show ();
			this.cadastrarUsuarioAction1.Activated += new global::System.EventHandler (this.OnCadastrarUsuarioAction1Activated);
			this.sairAction.Activated += new global::System.EventHandler (this.OnSairActionActivated);
			this.fixed1.Removed += new global::Gtk.RemovedHandler (this.OnFixed1Removed);
			this.menubar1.SelectionDone += new global::System.EventHandler (this.OnMenubar1SelectionDone);
		}
	}
}
